### ISSUE TITLE
Add godot as a "Programming Language"

### ISSUE THREAD

**Issue by ModProg** [beemstream/stream-collection-service#7]
Most Godot streamers will only have Godot in the title and not the language gdscript. So probably the best way to support that.

Hope this is the right repo for the issue :D

**Comment by beemstream** [comment]
Hey @ModProg, thanks for raising the issue, this is actually handled on the client side for now, please refer and raise the issue on [frontend-v2](https://github.com/beemstream/frontend-v2)
